# Generated by Django 5.0.3 on 2024-03-07 17:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id_deporte', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Deporte',
                'verbose_name_plural': 'Deportes',
                'db_table': 'deportes',
            },
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id_instalacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('iluminacion', models.BooleanField(default=False)),
                ('cubierta', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Instalacion',
                'verbose_name_plural': 'Instalaciones',
                'db_table': 'instalaciones',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('equipacion_principal', models.CharField(max_length=100)),
                ('equipacion_suplente', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('id_deporte', models.ForeignKey(db_column='id_deporte', on_delete=django.db.models.deletion.RESTRICT, to='AppTorremolinos.deporte')),
            ],
            options={
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipos',
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id_partido', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('puntos_local', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('puntos_visitante', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('id_deporte', models.ForeignKey(db_column='id_deporte', on_delete=django.db.models.deletion.RESTRICT, to='AppTorremolinos.deporte')),
                ('id_instalacion', models.ForeignKey(blank=True, db_column='id_instalacion', null=True, on_delete=django.db.models.deletion.RESTRICT, to='AppTorremolinos.instalacion')),
                ('id_local', models.ForeignKey(db_column='id_local', on_delete=django.db.models.deletion.RESTRICT, related_name='partidos_local', to='AppTorremolinos.equipo')),
                ('id_visitante', models.ForeignKey(db_column='id_visitante', on_delete=django.db.models.deletion.RESTRICT, related_name='partidos_visitante', to='AppTorremolinos.equipo')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'db_table': 'partidos',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id_jugador', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido1', models.CharField(max_length=20)),
                ('apellido2', models.CharField(blank=True, max_length=20, null=True)),
                ('dorsal', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('peso', models.PositiveIntegerField()),
                ('telefono', models.CharField(max_length=15)),
                ('id_equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.RESTRICT, to='AppTorremolinos.equipo')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'jugadores',
                'unique_together': {('id_equipo', 'dorsal')},
            },
        ),
    ]
